# Criar arrays uni e multidimensionais e manipular sua estrutura

### Facil// Crie um array 1D com 10 números e mostre seu shape e ndim

In [42]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,11])
print(a.shape)
print(a.ndim)



(10,)
1


### Converta um array 1D de 12 elementos em uma matriz 3x4 usando reshape.

In [16]:
a = np.zeros([12])
b = a.reshape(3,4)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Medio// Crie um array 3D (2x3x4) e mostre suas dimensões.

In [18]:
import numpy as np
a = np.zeros([3,3,4])
print(a.shape)
print(a.ndim)
print(a)

(3, 3, 4)
3
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### Medio// Modifique o formato de uma matriz 2x6 para 3x4.

In [ ]:
a = np.ones([2,6])
b = a.reshape(3,4)
print(a)
print(b)

(2, 6)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### dificil// Gere uma matriz 6x6 e transforme-a em um vetor 1D sem usar laços.

In [50]:
import random 
a =  np.random.randint(0,101,(6,6))
print(a)
b = a.reshape(36)
print(b)




[[33 75 18 73  9  4]
 [80 33 43 20 82 45]
 [27 16 27 27 78 86]
 [65 58 72 93 61 20]
 [56 39 79 54  1 58]
 [91 75 48 62 25 68]]
[33 75 18 73  9  4 80 33 43 20 82 45 27 16 27 27 78 86 65 58 72 93 61 20
 56 39 79 54  1 58 91 75 48 62 25 68]


### Desafio 1

In [ ]:
def tabuleiro(n1,n2):

    print(n1+n2)

n1 = input("linha")
n2 = input("coluna")
tabuleiro(n1,n2)


23


: 