In [7]:
import numpy as np 
import random as rd 

a = np.random.randint(0 ,11 , [100, 6])
print(a)
print(a.shape())
print(a.ndim())
print(a.size())

[[ 0  5  5  6  0  9]
 [ 7  1  5  3  3  0]
 [10 10  0  0  1  4]
 [ 2  1  3  6  1  7]
 [ 4  3  3  1  9  9]
 [ 6  8  0  2  7  0]
 [ 9  6  6  3  3  1]
 [ 8  4 10  3  6  7]
 [ 4  1  2  3  2  1]
 [ 4  1  6  4  0  8]
 [ 7  6  5  7  9  7]
 [ 1  4  5  3  2  7]
 [ 4  4  8 10  4  6]
 [ 3  9  3  4  5  6]
 [ 7  6  1  1  8  0]
 [ 8 10  1 10  7  3]
 [ 8  3  3  7  7  1]
 [ 2  5  5  1 10  1]
 [ 5  9  6  0  2  4]
 [ 3  6  0 10  5 10]
 [ 2  9  6  8  5  1]
 [10  8  4  0  2  8]
 [ 1  5  5  3  7  0]
 [ 0  8  1  2  8 10]
 [ 2  4  7  9  2  7]
 [ 3  0  1  7  9  5]
 [ 1  2  5  0  6 10]
 [ 9  2  9 10  3  3]
 [ 3  7 10  4  6  0]
 [ 7  0  1 10  0  8]
 [ 5  4  6 10  2  0]
 [ 9  6  5  5  9  5]
 [ 9 10  5 10  5  3]
 [ 4  0  9  1  9  1]
 [ 2  7  8  7  5  1]
 [ 0  3  0  1  7  1]
 [ 3  2  6 10  6  5]
 [ 3  3  5  6  6  9]
 [ 9  5  3  0  2  5]
 [ 3  6  6  5  0  6]
 [ 9  0  0  0  3  3]
 [ 4  5  4  4  7  3]
 [ 8 10  0  5  7  3]
 [ 3  5 10  5  6  2]
 [ 1  7  0 10  4 10]
 [ 4  2  3  2  1  7]
 [ 3  8  1  3 10  0]
 [ 3  2  1  6

TypeError: 'tuple' object is not callable