### 1)Considere que uma universidade registrou as notas de 100 alunos em 6 disciplinas, organizadas em uma matriz 2D, onde cada linha representa um aluno e cada coluna representa uma disciplina. Os valores das notas variam de 0 a 10.
### a) Utilizando a biblioteca NumPy, crie um array chamado notas com dimensão (100, 6), contendo valores aleatórios entre 0 e 10. Em seguida, exiba o shape, o número de dimensões (ndim) e o total de elementos (size) do array.

In [30]:
import numpy as np 
import random as rd 

a = np.random.randint(0 ,11 , [100, 6])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 6  3  8  7  7  2]
 [ 6  0  1  4  5  8]
 [ 2  0  5  9  3  0]
 [ 2  1 10  2  7  3]
 [ 6  1  3  4  0  9]
 [ 7  9  0  4  8  1]
 [ 0  9  1  6  8  8]
 [ 2  7 10  5  9 10]
 [ 3  9  9  0 10  0]
 [ 7  7  7  1  8  8]
 [ 3 10  1  3  6  0]
 [ 5  3  9  7  4  1]
 [ 7  3 10  8  9  1]
 [ 3  3  4  5  1  5]
 [ 0  9  2  9  5  3]
 [ 3  8  0 10  9  5]
 [10  8  0 10  3  1]
 [ 4  5  0  2  2  9]
 [ 6  7  2  8  6 10]
 [ 7  7  4  4  4  9]
 [ 5  7  8 10  3  8]
 [ 0  2  6  8  9  2]
 [ 6  1  3  6  2  6]
 [ 7  3  9  0  1  9]
 [ 0  9  5  8  6  5]
 [ 7  9  5 10  0  5]
 [ 3  1  5  1  5  7]
 [ 5  4 10 10  8  8]
 [ 5  2  0 10  1  0]
 [ 0  1  9  9  4  9]
 [ 5  9  5  3  4  0]
 [ 1 10  0  6  7  0]
 [ 8  1  8  2  8  6]
 [ 6  6  9  8  1  7]
 [ 9 10  7  8  1  5]
 [ 8  3  7  8  6  5]
 [ 9  3  8  9  3  5]
 [ 9  2  6  3  2  2]
 [ 7  2 10  3  1  4]
 [ 8  4  0  5  8  3]
 [ 2  1  2  2  3  8]
 [ 7  3  1  6  8  4]
 [10  0  4 10  7  9]
 [ 4  6  6  2 10  7]
 [ 4  4  5  2  6  0]
 [ 6  7  1  2  6  9]
 [ 7  2  8  7  5  4]
 [10  1  7  0

### b) Reestruture o array para o formato (50, 12) e depois retorne ao formato original (100, 6), garantindo que os dados não sejam perdidos.

In [31]:
b = a.reshape([50,12])
print(b)
b = a.reshape([100,6])
print(b)

[[ 6  3  8  7  7  2  6  0  1  4  5  8]
 [ 2  0  5  9  3  0  2  1 10  2  7  3]
 [ 6  1  3  4  0  9  7  9  0  4  8  1]
 [ 0  9  1  6  8  8  2  7 10  5  9 10]
 [ 3  9  9  0 10  0  7  7  7  1  8  8]
 [ 3 10  1  3  6  0  5  3  9  7  4  1]
 [ 7  3 10  8  9  1  3  3  4  5  1  5]
 [ 0  9  2  9  5  3  3  8  0 10  9  5]
 [10  8  0 10  3  1  4  5  0  2  2  9]
 [ 6  7  2  8  6 10  7  7  4  4  4  9]
 [ 5  7  8 10  3  8  0  2  6  8  9  2]
 [ 6  1  3  6  2  6  7  3  9  0  1  9]
 [ 0  9  5  8  6  5  7  9  5 10  0  5]
 [ 3  1  5  1  5  7  5  4 10 10  8  8]
 [ 5  2  0 10  1  0  0  1  9  9  4  9]
 [ 5  9  5  3  4  0  1 10  0  6  7  0]
 [ 8  1  8  2  8  6  6  6  9  8  1  7]
 [ 9 10  7  8  1  5  8  3  7  8  6  5]
 [ 9  3  8  9  3  5  9  2  6  3  2  2]
 [ 7  2 10  3  1  4  8  4  0  5  8  3]
 [ 2  1  2  2  3  8  7  3  1  6  8  4]
 [10  0  4 10  7  9  4  6  6  2 10  7]
 [ 4  4  5  2  6  0  6  7  1  2  6  9]
 [ 7  2  8  7  5  4 10  1  7  0  7  3]
 [ 4  3  2  5  0  1  8  2  6 10  4  6]
 [ 1  4  6  2  4  5  9  4

### c) Acesse e exiba: as notas do aluno de índice 10; as notas da disciplina de índice 3; e as notas dos alunos de índice 20 a 30 nas disciplinas de índice 2 a 4.

In [32]:
print((a[10,3]))
print((a[20:30 ,2:4]))




3
[[ 8 10]
 [ 6  8]
 [ 3  6]
 [ 9  0]
 [ 5  8]
 [ 5 10]
 [ 5  1]
 [10 10]
 [ 0 10]
 [ 9  9]]


### d) Substitua todas as notas menores que 5 por 5, sem utilizar estruturas de repetição (laços).

In [34]:
print(a)
a[a < 5 ] = 5
print (a)

[[ 6  5  8  7  7  5]
 [ 6  5  5  5  5  8]
 [ 5  5  5  9  5  5]
 [ 5  5 10  5  7  5]
 [ 6  5  5  5  5  9]
 [ 7  9  5  5  8  5]
 [ 5  9  5  6  8  8]
 [ 5  7 10  5  9 10]
 [ 5  9  9  5 10  5]
 [ 7  7  7  5  8  8]
 [ 5 10  5  5  6  5]
 [ 5  5  9  7  5  5]
 [ 7  5 10  8  9  5]
 [ 5  5  5  5  5  5]
 [ 5  9  5  9  5  5]
 [ 5  8  5 10  9  5]
 [10  8  5 10  5  5]
 [ 5  5  5  5  5  9]
 [ 6  7  5  8  6 10]
 [ 7  7  5  5  5  9]
 [ 5  7  8 10  5  8]
 [ 5  5  6  8  9  5]
 [ 6  5  5  6  5  6]
 [ 7  5  9  5  5  9]
 [ 5  9  5  8  6  5]
 [ 7  9  5 10  5  5]
 [ 5  5  5  5  5  7]
 [ 5  5 10 10  8  8]
 [ 5  5  5 10  5  5]
 [ 5  5  9  9  5  9]
 [ 5  9  5  5  5  5]
 [ 5 10  5  6  7  5]
 [ 8  5  8  5  8  6]
 [ 6  6  9  8  5  7]
 [ 9 10  7  8  5  5]
 [ 8  5  7  8  6  5]
 [ 9  5  8  9  5  5]
 [ 9  5  6  5  5  5]
 [ 7  5 10  5  5  5]
 [ 8  5  5  5  8  5]
 [ 5  5  5  5  5  8]
 [ 7  5  5  6  8  5]
 [10  5  5 10  7  9]
 [ 5  6  6  5 10  7]
 [ 5  5  5  5  6  5]
 [ 6  7  5  5  6  9]
 [ 7  5  8  7  5  5]
 [10  5  7  5

### e) Aplique um bônus de +0.5 em todas as notas utilizando operações vetorizadas.

In [42]:
print(a  + 0.5)
print(np.sum(a))


[[ 6.5  5.5  8.5  7.5  7.5  5.5]
 [ 6.5  5.5  5.5  5.5  5.5  8.5]
 [ 5.5  5.5  5.5  9.5  5.5  5.5]
 [ 5.5  5.5 10.5  5.5  7.5  5.5]
 [ 6.5  5.5  5.5  5.5  5.5  9.5]
 [ 7.5  9.5  5.5  5.5  8.5  5.5]
 [ 5.5  9.5  5.5  6.5  8.5  8.5]
 [ 5.5  7.5 10.5  5.5  9.5 10.5]
 [ 5.5  9.5  9.5  5.5 10.5  5.5]
 [ 7.5  7.5  7.5  5.5  8.5  8.5]
 [ 5.5 10.5  5.5  5.5  6.5  5.5]
 [ 5.5  5.5  9.5  7.5  5.5  5.5]
 [ 7.5  5.5 10.5  8.5  9.5  5.5]
 [ 5.5  5.5  5.5  5.5  5.5  5.5]
 [ 5.5  9.5  5.5  9.5  5.5  5.5]
 [ 5.5  8.5  5.5 10.5  9.5  5.5]
 [10.5  8.5  5.5 10.5  5.5  5.5]
 [ 5.5  5.5  5.5  5.5  5.5  9.5]
 [ 6.5  7.5  5.5  8.5  6.5 10.5]
 [ 7.5  7.5  5.5  5.5  5.5  9.5]
 [ 5.5  7.5  8.5 10.5  5.5  8.5]
 [ 5.5  5.5  6.5  8.5  9.5  5.5]
 [ 6.5  5.5  5.5  6.5  5.5  6.5]
 [ 7.5  5.5  9.5  5.5  5.5  9.5]
 [ 5.5  9.5  5.5  8.5  6.5  5.5]
 [ 7.5  9.5  5.5 10.5  5.5  5.5]
 [ 5.5  5.5  5.5  5.5  5.5  7.5]
 [ 5.5  5.5 10.5 10.5  8.5  8.5]
 [ 5.5  5.5  5.5 10.5  5.5  5.5]
 [ 5.5  5.5  9.5  9.5  5.5  9.5]
 [ 5.5  9.