### 1)Considere que uma universidade registrou as notas de 100 alunos em 6 disciplinas, organizadas em uma matriz 2D, onde cada linha representa um aluno e cada coluna representa uma disciplina. Os valores das notas variam de 0 a 10.
### a) Utilizando a biblioteca NumPy, crie um array chamado notas com dimensão (100, 6), contendo valores aleatórios entre 0 e 10. Em seguida, exiba o shape, o número de dimensões (ndim) e o total de elementos (size) do array.

In [9]:
import numpy as np 
import random as rd 

a = np.random.randint(0 ,11 , [100, 6])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 4  4  5  3  0  8]
 [ 4  5  5  8  3  9]
 [ 6  6  6  3  2  2]
 [ 2  1  5  6  0  3]
 [ 4  8  2  1  8  6]
 [ 5  8  0  4  8  2]
 [ 5 10  7  1  7  2]
 [ 2 10  1  1  2  4]
 [ 4  9  0  4  5  7]
 [ 2  2  7  9 10  1]
 [ 8  7  6  3  3  6]
 [ 0  5  3  4  4  8]
 [ 3  9  9  6  8  7]
 [ 6  8  5  9  1  6]
 [ 9  9  8  3  2  7]
 [ 9  6  1  3  5  3]
 [ 5  0  6  3  9  7]
 [ 6  3  8  5  1 10]
 [10  0  8  2  1  0]
 [ 3  3  7  4  8  3]
 [ 9  9  6  2  0 10]
 [ 3 10  3  1  7  5]
 [ 8  6  5  4  8  4]
 [ 7  2  0  7 10  1]
 [ 9  4  9  2  3  0]
 [ 2  0  5  2  1  6]
 [ 9  4  4  8  4  1]
 [ 0 10  2  0  9  6]
 [ 6  2  7  2  9  6]
 [ 7  8  0  6  6  7]
 [ 5  0  3  3  9  8]
 [ 4 10  0  0  3  3]
 [ 7  8  4  0  8  0]
 [ 5  9  7 10  6  8]
 [ 7  5  0 10  3  1]
 [ 0  2  8  2  7  7]
 [ 6  5  9  7  4  8]
 [ 1  1  1  4  2  6]
 [ 8  8  2  6  6  7]
 [10  7  3  8  9  7]
 [ 8  7  1  1  2  4]
 [ 7  2  7  1  9  6]
 [ 1  2  5  4  1  6]
 [ 0 10  1  8  8 10]
 [ 6  0  7  6 10  1]
 [ 9  4  5  0  6  1]
 [ 1  2  1  9 10  3]
 [ 7  5  7  6

In [ ]:
b = a.reshape([50,12])
print(b)


[[ 4  4  5  3  0  8  4  5  5  8  3  9]
 [ 6  6  6  3  2  2  2  1  5  6  0  3]
 [ 4  8  2  1  8  6  5  8  0  4  8  2]
 [ 5 10  7  1  7  2  2 10  1  1  2  4]
 [ 4  9  0  4  5  7  2  2  7  9 10  1]
 [ 8  7  6  3  3  6  0  5  3  4  4  8]
 [ 3  9  9  6  8  7  6  8  5  9  1  6]
 [ 9  9  8  3  2  7  9  6  1  3  5  3]
 [ 5  0  6  3  9  7  6  3  8  5  1 10]
 [10  0  8  2  1  0  3  3  7  4  8  3]
 [ 9  9  6  2  0 10  3 10  3  1  7  5]
 [ 8  6  5  4  8  4  7  2  0  7 10  1]
 [ 9  4  9  2  3  0  2  0  5  2  1  6]
 [ 9  4  4  8  4  1  0 10  2  0  9  6]
 [ 6  2  7  2  9  6  7  8  0  6  6  7]
 [ 5  0  3  3  9  8  4 10  0  0  3  3]
 [ 7  8  4  0  8  0  5  9  7 10  6  8]
 [ 7  5  0 10  3  1  0  2  8  2  7  7]
 [ 6  5  9  7  4  8  1  1  1  4  2  6]
 [ 8  8  2  6  6  7 10  7  3  8  9  7]
 [ 8  7  1  1  2  4  7  2  7  1  9  6]
 [ 1  2  5  4  1  6  0 10  1  8  8 10]
 [ 6  0  7  6 10  1  9  4  5  0  6  1]
 [ 1  2  1  9 10  3  7  5  7  6  1  0]
 [ 3 10  3  8  7  1  8  2  5  7  2  0]
 [ 7  7  4  5  8  6  0  0