In [ ]:
import numpy as np 
import random as rd 

a = np.random.randint(0 ,11 , [100, 6])
print(a)
print(a.shape())
print(a.ndim())
print(a.)

[[ 1  4  1  8  5  4]
 [ 0  0  9  7  3  2]
 [ 5  3  2  0  7  5]
 [ 4  0  2  9  9  3]
 [10  4  2  1 10  6]
 [ 7  8 10  4  7  7]
 [ 9  0  2  2  7  8]
 [10  5 10  5  5  2]
 [ 5  5  9  6  1  2]
 [ 6  4  8  3  0  9]
 [ 7  4  0  7  9  8]
 [ 0  0  1  0  4  4]
 [ 0  6  4  0  4  2]
 [ 3  6  8  6  6  6]
 [ 0  1  0  9 10  4]
 [ 9  6  3 10  3  7]
 [ 8  0  8  6 10  8]
 [ 1  1  5  1  3  6]
 [ 9  5  8 10  0  2]
 [ 5  1  7  1  1  8]
 [ 8  1  8  7  9 10]
 [ 7  0  6  4  7  9]
 [ 8  8  3  3  8  4]
 [ 9  4  2  1  5  9]
 [ 5  6  8  0  8  3]
 [ 8  4 10  9  2  9]
 [ 2  2  8  9  2  8]
 [ 2  0  8  2  5  0]
 [ 0  7  7  7  7 10]
 [ 5  2 10  2  7 10]
 [ 9  2  6  3  0  9]
 [ 7  8  1  4  1 10]
 [ 9  4  8  7  2 10]
 [ 2  8  3  8  6  8]
 [10  9  5  0  4  5]
 [ 0 10  8  2  3  8]
 [ 0  7  5  7  7  9]
 [ 9  3  9  7  1  8]
 [ 2  6  9  0  2  5]
 [ 5  8  6  2  9  8]
 [ 2  9  7  1 10  3]
 [ 0  2 10  7  6  2]
 [ 5 10 10  0 10  9]
 [ 6  0  2  2  8  9]
 [ 8  9  2  0  6  4]
 [ 9  9  9  9  6  7]
 [ 0  7  5  1  2  4]
 [ 6  3 10  6